### ISSUE TITLE
incoterms_id in intrastat_product module

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/intrastat-extrastat#102]
Hi,

I'm not sure if it is a real issue or not.

**On vendor invoices**:

After installing this module, you will have 2 incoterms fields:

1- incoterm_id --> from standard Odoo

2- incoterms_id --> from intrastat_product module

What's the point on having 2 incoterm related fields; one from standard and another one coming from intrastat_product module? Am I missing something?

![Captura de pantalla 2020-08-12 a las 17 13 06](https://user-images.githubusercontent.com/32449357/90033108-6041a300-dcbf-11ea-925d-47e21fc7dd4c.png)

@luc-demeyer @alexis-via @pedrobaeza 

THX

**Comment by alexis-via** [comment]
When I look at the source code of the module intrastat_product, I don't see any field incoterms_id on account.move/account.invoice (I looked in v14, v13 and v12), cf https://github.com/OCA/intrastat-extrastat/blob/14.0/intrastat_product/models/account_move.py

I think this field incoterms_id comes from another module. Please re-open the ticket with information about the version of Odoo.
