### ISSUE TITLE
14.0 mig : invoice domain should be based on fiscal position in stead of country

### ISSUE THREAD

**Issue by luc-demeyer** [OCA/intrastat-extrastat#110]
Up till now the default domain to select intrastat transactions is based upon invoices to/from EU countries.
I propose that we change in 14.0 the logic to be based upon the "Intra EU" fiscal position.

On the Belgian market transactions subject to the 'intrastat' declaration are also subject to the 'intracommunity' tax declaration.
In the 13.0 version of the Belgium localisation module I already replaced the domain query, cf. 
https://github.com/Noviat/noviat-apps/blob/012c9a254b101c405126b1c0ce5276a0a9c16d9e/l10n_be_intrastat_product/models/l10n_be_intrastat_product_declaration.py#L219

But since these rules are decided on an european level, this should be applicable for all EU countries.
As a consequence I propose that for the 14.0 migration we add an 'intrastat' boolean to the fiscal position and base the domain on invoices with fiscal positions marked as 'intrastat'. In the localisation modules we can add the logic to set this flag automatically on the standard Intra EU fiscal position.

To give a concrete example why the country tabel is wrong:
If you ship goods to a customer without VAT number in an EU country that this shipment must not be included in the intrastat declaration.

**Comment by alexis-via** [comment]
I agree with this idea.
About your last point, the scenario was handled via the boolean exclude_from_intrastat_if_present on account.tax and it was working fine.
The advantage of this solution is that it's easier to configure, because you just a few fiscal positions instead of dozens of taxes.

**Comment by alexis-via** [comment]
Now that this has been implemented in v14, let's close it.
