### ISSUE TITLE
Field hs_code_id on products and company_dependent

### ISSUE THREAD

**Issue by alexis-via** [OCA/intrastat-extrastat#126]
Currently, in the module product_harmonized_system, the field hs_code_id on product.template and on product.category has company_dependent=True, cf
https://github.com/OCA/intrastat-extrastat/blob/14.0/product_harmonized_system/models/product_template.py#L16

Is it really a good idea ? Sometimes I think that it has been introduced by someone who needed it on a project in a very special context, but it adds extra complexity for everybody. In a standard scenario, HS code should not depend on company. HS code should be considered as "physical" property of a product, like the weight, which doesn't depend on the company.

What do you think ? Should be consider to switch back to company_dependent=False on v15 ?

**Comment by pedrobaeza** [comment]
Yes, I think the nature of the product shouldn't changed between companies. We can even consider it for v14, but doing a migration script for "materializing" the value correctly in new physical column. This migration script will be needed anyway when switching.

**Comment by azucenatrey** [comment]
Hello, we just detected the problem in 12.0 and we are going to make a modification to fix it.
When we have it, we will propose a PR to solve the issue.
