### ISSUE TITLE
default branch 10.0

### ISSUE THREAD

**Issue by simahawk** [OCA/intrastat-extrastat#13]
shouldn't we have 10.0 as default branch as all the other repos?

**Comment by pedrobaeza** [comment]
@alexis-via did you change it?

**Comment by alexis-via** [comment]
I don't have the permissions to do such a change... I don't have access to the Settings tab.

**Comment by pedrobaeza** [comment]
Well, I have changed it then. Weird...

**Comment by alexis-via** [comment]
@pedrobaeza I don't have this kind of permission on any of the OCA projets on which I am in the PSC. It seems reserved to some users with "super-powers".

**Comment by pedrobaeza** [comment]
We are studying that internally on the board, as that super-power also allows to delete branches and make to lose all the OCA stuff. The weird thing is that the default branch didn't change when migrating branches (maybe an error due to GH rate limits...)
