### ISSUE TITLE
Weight not calculated when the Uom is not Units

### ISSUE THREAD

**Issue by jalzaga** [OCA/intrastat-extrastat#143]
When the product has a unit of measure different from units or with category different from units, e.g., meters or m2, the weight is not calculated. The module gives the message: Conversion from unit of measure 'm' to 'Kg' is not implemented yet. It is needed for product 'xxxx'
The supplementary units field is correctly put into the declaration when it is set in the intrastat code but the weight is not calculated and is set to zero.

**Comment by luc-demeyer** [comment]
the net weight is optional for the commodity codes for which
the supplementary units are mandatory hence I don't think this is an issue

![image](https://user-images.githubusercontent.com/7706945/136667072-31469b6c-92ea-407a-a5d8-44a82bcf9664.png)
