### ISSUE TITLE
intrastat: country of origin

### ISSUE THREAD

**Issue by rousseldenis** [OCA/intrastat-extrastat#147]
Hi all,

I've a requirement about the country of origin for a product (origin_country_id).

In order to not create a new product for each country of origin, we try to find the best way to implement it.

For instance, one sold product 'Bananas' with different origin countries.

Is someone has faced this kind of issue ?

I thought about using variants but what impact in terms of warehouse flows ? We envisaged also to set the information on lots. But that has the disadvantage of breaking the intrastat_product module code.

Thanks for your answers.

@alexis-via @luc-demeyer

**Comment by luc-demeyer** [comment]
Why not creating two different products ? If the bananas come from two countries than you probably have also two different suppliers 
You can also make a small custom module for this specific requirement and generate the 'account.move.intrastat.line' with the correct country of origin when creating the supplier invoice from the PO.

**Comment by rousseldenis** [comment]
> Why not creating two different products ? If the bananas come from two countries than you probably have also two different suppliers You can also make a small custom module for this specific requirement and generate the 'account.move.intrastat.line' with the correct country of origin when creating the supplier invoice from the PO.

Because customer does not want to manage several products.

Here we speak about the 'made in ____' field which represents the fabrication country. So, we can have a product from country X supplied by partner of country Y (with all variants).

**Comment by rousseldenis** [comment]
@luc-demeyer You can find my implementation there : https://github.com/OCA/intrastat-extrastat/pull/150/files
