### ISSUE TITLE
[RFC] intrastat_product: Add an Intrastat summary in the invoice report

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/intrastat-extrastat#175]
One of my customers has asked for having an Intrastat summary on each invoice for their customers to be aware about the HS codes, weights and so on to fill. I think this can be something that can be done in this module instead of handling it on each localization.

It can be an extra page in the same invoice report with a table with the following cells:

- Product reference
- Product name
- HS code
- Weight
- Origin country

And it would be something opt-in to be marked on the commercial partner.

What do you think? @alexis-via @luc-demeyer

**Comment by luc-demeyer** [comment]
@pedrobaeza 
this is already there : cf. intrastat transaction details.

**Comment by pedrobaeza** [comment]
But is there a report to give it to the customer?

**Comment by luc-demeyer** [comment]
the info is in the invoice hence adapt the invoice qweb template and it's done

**Comment by pedrobaeza** [comment]
And this RFC is for that task :wink:
