### ISSUE TITLE
[16.0] intrastat_product : uom_id in supplementary units shouldn't be required in form view

### ISSUE THREAD

**Issue by metaminux** [OCA/intrastat-extrastat#223]
## Module
intrastat_product

## Describe the bug
In Supplementary Units (intrastat.unit) the field **uom_id** is a Many2one to native Odoo model Unit of Measures (uom.uom)
In the form view, this field is set as required="1", but we can have intrastat unit that will never be mapped to an odoo unit

## To Reproduce
**16.0**:

1. Just install the intrastat_product module

**Expected behavior**
This field shouldn't be set as required

**Additional context**
80c0e7c78294bb8a5ab1e5508172dfa92da69ae3 already fixed this but was reverted in 23209812b4a5cfb34d6e20c736293bd0a7aaf421
@luc-demeyer and @alexis-via Is there a reason why ?

**Comment by pedrobaeza** [comment]
It seems a mistake pushing changes. Please do a PR amending it.
