### ISSUE TITLE
[10] ICP report for multicompany

### ISSUE THREAD

**Issue by yung-wang** [OCA/intrastat-extrastat#26]
I'm using the ICP report in a multicompany environment. When I open the menu the view l10n_nl.report.intrastat tree shows me all the reports of all the companies. There is a recordrule missing to display on the report of the current logged in company. Please add record rule with the following Domain Filter for version 10 and above:

['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]

**Comment by astirpe** [comment]
@yung-wang in your case, the `company_id` field is defined in module **l10n_nl_intrastat**. So you should open an issue in https://github.com/OCA/l10n-netherlands repository instead.

**Comment by yung-wang** [comment]
Ok, see referred issue
