### ISSUE TITLE
[15.0] requirements.txt: python-stdnum version incompatibility

### ISSUE THREAD

**Issue by zamberjo** [OCA/intrastat-extrastat#282]
Both the [odoo](https://github.com/odoo/odoo/blob/15.0/requirements.txt#L51) and [OCB](https://github.com/oca/ocb/blob/15.0/requirements.txt#L51) repositories for version 15.0 use python-stdnum==1.13 while this repository adds the python-stdnum>=1.16 dependency.

Since this version has been around for quite some time, I guess that OCB should be modified so that there is no version incompatibility, is that right @victoralmau, how do you have it implemented?

**Comment by victoralmau** [comment]
This requirement was added in 14.0 at https://github.com/OCA/intrastat-extrastat/pull/120 and in v15 it is still required as set in the `intrastat_product` manifest (https://github.com/OCA/intrastat-extrastat/blob/15.0/intrastat_product/__manifest__.py#L25).

**Comment by zamberjo** [comment]
This does not solve the conflict with a dependency in Odoo and OCB. Does this imply a PR for OCB by removing the version restriction?

**Comment by victoralmau** [comment]
IMO no PR to OCB is necessary for this.

Ping @pedrobaeza

**Comment by pedrobaeza** [comment]
Yeah, the deployment system you use should take Odoo/OCB requirements and install them, and then specific requirements for extra modules should be put on top and override the versions if needed. `==` put on Odoo requirements is for assuring the same compatibility across Linux distributions, but I don't see incompatibilities in newer versions.
