### ISSUE TITLE
9.0 branch

### ISSUE THREAD

**Issue by hbrunn** [OCA/intrastat-extrastat#4]
what is the proper way to create an empty 9.0 branch here and fill it from 8? Or should be just push the current 8 there and make everything uninstallable manually?

**Comment by pedrobaeza** [comment]
I'll run migrate_branch.sh script when you tell me that it's everything OK.

**Comment by hbrunn** [comment]
what are the conditions for everything being okay? (and as I have you in conversation anyways, can you do the same thing for https://github.com/OCA/edi/{9.0,10.0})?

**Comment by pedrobaeza** [comment]
Not having opened PRs in the source branch.

**Comment by hbrunn** [comment]
aha! Just merge the readme update here, and the one in edi also looks good to merge. Thanks, closing this then

**Comment by hbrunn** [comment]
does the script also create milestones or should they be added manually?

**Comment by alexis-via** [comment]
@hbrunn FYI, I started porting the modules to v10, and I'll finish it in the coming days/weeks. As the code for v9 will be very close to the code for v10, maybe we can sync our work.

**Comment by hbrunn** [comment]
@alexis-via great to hear, then I'll review your 10 PR when you're done and port from there

**Comment by pedrobaeza** [comment]
Milestones are created with the script. Should I run then just now?

**Comment by hbrunn** [comment]
no complaints and a please from my side

**Comment by pedrobaeza** [comment]
@alexis-via, do you want me to run the script already for 9.0/10.0 and rebase your PR to reduce the number of commits?
