### ISSUE TITLE
Empty Group

### ISSUE THREAD

**Issue by schout-it** [OCA/intrastat-extrastat#48]
https://github.com/OCA/intrastat/blob/23b36e070db1440ccd720efb0edc321820629482/intrastat_base/views/product_template.xml#L16

Is there a reason why this group is still visible?
because if the intrastat_product module is not installed, there is an empty group with a name in the formview.

**Comment by pedrobaeza** [comment]
There's not too much sense to install base module without another one, so we don't care too much about the tab being empty when you haven't installed the dependent module.

**Comment by luc-demeyer** [comment]
What is the concrete use case for installing intrastat_base without intrastat_product ?

**Comment by schout-it** [comment]
I'll close this issue, 
Was the residue of a migration from a v7.0
