### ISSUE TITLE
[HS code] Why is it company dependent ?

### ISSUE THREAD

**Issue by PierrickBrun** [OCA/intrastat-extrastat#53]
I don't understand why we should duplicate H.S. codes between companies, isn't it just static data used by every company in the db ?

Example : https://github.com/OCA/intrastat-extrastat/blob/59b1959ba64aeee673699bf61fe4dbd34d72479c/product_harmonized_system/models/hs_code.py#L34

**Comment by bealdav** [comment]
i.e case with 23 companies !

ping @alexis-via

**Comment by luc-demeyer** [comment]
The last digits are different between the countries but if you have multiple legal entities in the same country than we should allow to share the codes (and in the meanwhile the PR to fix this is merged).

**Comment by PierrickBrun** [comment]
Thanks for the explanation
